name: pycurious
channels:
    - default
    - conda-forge
dependencies:
    - python=3.7
    - pip
    - numpy
    - scipy
    - cython
    # Optional dependencies
    - jupyter
    - matplotlib
    - pyproj
    - cartopy
